export const skills = {
  langs_frams: [
    "HTML",
    "CSS",
    "Ruby",
    "Ruby on Rails",
    "Javascript",
    "React",
    "NodeJS",
  ],
  libs_tools: [
    "Sass",
    "Bootstrap",
    "Styled Components",
    "Framer Motion",
    "Redux",
    "Jest",
    "Axios",
    "Rspec",
    "ChartJs",
    "Phaser 3",
  ],
  soft: [
    "Remote Work",
    "Pair Programming",
    "Agile Methods",
    "Fluent English",
    "Communication",
    "Self Learner",
    "Git",
    "Github",
    "Github Actions",
    "Linters",
    "Yarn / Npm",
    "VScode",
    "Linux",
  ],
};
